import type { Ticket } from "./tickets.ts";

const entries: [
  string,
  string,
  string,
  Ticket["status"],
  Ticket["priority"],
  string,
  string,
][] = [
  [
    "Checkout returns to cart after address edit",
    "Maya Chen",
    "Checkout",
    "Open",
    "Urgent",
    "Alex",
    "Changing a saved delivery address returns the customer to the cart. Reproduce with a saved address and at least two items. Confirm whether the checkout state survives the address update.",
  ],
  [
    "Cannot download March invoice",
    "Jonas Meyer",
    "Billing",
    "In progress",
    "High",
    "Sam",
    "The invoice download shows a blank tab. The customer has tried Chrome and Safari. Check the generated PDF response and download filename.",
  ],
  [
    "Order confirmation has the wrong timezone",
    "Lina Petrova",
    "Orders",
    "Open",
    "Normal",
    "Unassigned",
    "Confirmation emails show UTC instead of the store timezone. The order detail screen displays the expected local time.",
  ],
  [
    "Invite link expires immediately",
    "Owen Brooks",
    "Accounts",
    "Waiting",
    "High",
    "Alex",
    "The team invitation reports that the link has expired on first use. Waiting for the customer to confirm when the invitation was received.",
  ],
  [
    "Shipping label cuts off apartment number",
    "Eva Santos",
    "Shipping",
    "Open",
    "High",
    "Sam",
    "Long address lines are clipped on the printable label. The complete address appears in order details.",
  ],
  [
    "Product search ignores accented characters",
    "Milan Novak",
    "Catalog",
    "In progress",
    "Normal",
    "Alex",
    "Searching without accents does not return matching accented product names. Review normalization and search behavior.",
  ],
  [
    "Request to change billing contact",
    "Grace Taylor",
    "Billing",
    "Resolved",
    "Low",
    "Sam",
    "Billing contact was updated and the customer confirmed the new address.",
  ],
  [
    "Saved cart opens empty on another device",
    "Leo Martin",
    "Checkout",
    "Open",
    "High",
    "Unassigned",
    "The signed-in customer saved a cart on mobile and sees an empty cart on desktop.",
  ],
  [
    "CSV export uses mixed date formats",
    "Nora Anders",
    "Orders",
    "Open",
    "Normal",
    "Alex",
    "The order export mixes ISO dates and local dates. Align the formats and document the timezone.",
  ],
  [
    "Notification preference does not persist",
    "Aisha Khan",
    "Accounts",
    "In progress",
    "Normal",
    "Sam",
    "Turning off weekly summaries is not preserved after refreshing the settings screen.",
  ],
  [
    "Refund total includes cancelled item",
    "Noah Wilson",
    "Billing",
    "Open",
    "Urgent",
    "Unassigned",
    "The refund preview includes an item that was cancelled before payment. Verify the preview before issuing any refund.",
  ],
  [
    "Delivery estimate missing on mobile",
    "Sofia Rossi",
    "Shipping",
    "Waiting",
    "Normal",
    "Alex",
    "Delivery estimates are visible on desktop but not on a narrow screen. Waiting for the device and browser version.",
  ],
  [
    "Keyboard focus skips quantity field",
    "Theo Evans",
    "Catalog",
    "Open",
    "Normal",
    "Sam",
    "The cart quantity control is skipped while using Tab. Inspect the control focus order.",
  ],
  [
    "Duplicate message in order timeline",
    "Emma Davis",
    "Orders",
    "Resolved",
    "Low",
    "Alex",
    "A duplicated shipment update was removed. The timeline now contains one event.",
  ],
  [
    "Need a copy of last year invoices",
    "Paul Fischer",
    "Billing",
    "Waiting",
    "Low",
    "Unassigned",
    "Customer requested a consolidated set of invoices. Waiting for confirmation of the date range.",
  ],
  [
    "Password reset success screen is blank",
    "Sara Ali",
    "Accounts",
    "Open",
    "High",
    "Alex",
    "The password is updated successfully but the completion screen contains no next action.",
  ],
  [
    "Category filter resets after opening item",
    "Oscar Lee",
    "Catalog",
    "In progress",
    "Normal",
    "Sam",
    "Returning from a product resets the chosen category and the scroll position.",
  ],
  [
    "Clarify pickup instructions",
    "Julia Kim",
    "Shipping",
    "Resolved",
    "Low",
    "Alex",
    "Pickup instructions were clarified and confirmed by the customer.",
  ],
];

export function createSeed(): Ticket[] {
  return entries.map(
    (
      [title, customer, category, status, priority, assignee, description],
      index,
    ) => {
      const createdAt = new Date(
        Date.UTC(2026, 9, 8, 9, 0) - index * 3_600_000,
      ).toISOString();
      return {
        id: `SD-${1042 - index}`,
        title,
        customer,
        category,
        status,
        priority,
        assignee,
        description,
        createdAt,
        updatedAt: createdAt,
        activity: [{ at: createdAt, text: "Request created" }],
      };
    },
  );
}
